// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

exports.Runner = (function() {
  function Runner(options, filenames) {
    var f, _i, _len;

    this.options = options;
    this.yellow = __bind(this.yellow, this);
    this.red = __bind(this.red, this);
    this.green = __bind(this.green, this);
    if (this.options.noColor || this.options.noColour) {
      this.cNorm = this.cRed = this.cGreen = "";
    } else {
      this.cNorm = "\u001B[39m";
      this.cRed = "\u001B[31m";
      this.cGreen = "\u001B[32m";
      this.cYellow = "\u001B[33m";
    }
    this.total_failed = 0;
    this.total_passed = 0;
    this.queue = [];
    this.coffee_loaded = false;
    for (_i = 0, _len = filenames.length; _i < _len; _i++) {
      f = filenames[_i];
      this.loadFile(f);
    }
    this.start_time = Date.now();
  }

  Runner.prototype.green = function(text) {
    return "" + this.cGreen + text + this.cNorm;
  };

  Runner.prototype.red = function(text) {
    return "" + this.cRed + text + this.cNorm;
  };

  Runner.prototype.yellow = function(text) {
    return "" + this.cYellow + text + this.cNorm;
  };

  Runner.prototype.getNext = function() {
    return this.queue.shift();
  };

  Runner.prototype.run = function(finished) {
    var current;

    this.finished = finished;
    if (current = this.getNext()) {
      return this.runClass(current);
    }
  };

  Runner.prototype.onAssertionPass = function() {};

  Runner.prototype.onAssertionFail = function(error) {};

  Runner.prototype.onStartTest = function() {};

  Runner.prototype.onEndTest = function() {};

  Runner.prototype.onStartClass = function() {};

  Runner.prototype.onEndClass = function() {};

  Runner.prototype.onStartFile = function() {};

  Runner.prototype.onEndFile = function() {};

  Runner.prototype.runClass = function(_arg) {
    var cls, error, filename, func, next, obj,
      _this = this;

    filename = _arg[0], cls = _arg[1], func = _arg[2];
    next = this.getNext();
    if (this.current_filename !== filename) {
      if (this.current_filename != null) {
        this.onEndFile(this.current_filename);
      }
      this.onStartFile(filename);
      this.current_filename = filename;
    }
    try {
      obj = new func(this.options);
    } catch (_error) {
      error = _error;
      console.log(error.stack);
      return;
    }
    obj.on("pass", function() {
      _this.total_passed++;
      return _this.onAssertionPass();
    });
    obj.on("fail", function(error) {
      _this.total_failed++;
      return _this.onAssertionFail(error);
    });
    obj.on("startTest", function(name) {
      return _this.onStartTest(name);
    });
    obj.on("endTest", function(name, test) {
      return _this.onEndTest(name, test);
    });
    this.onStartClass(cls);
    return (function(next, cls) {
      return obj.run(function(results) {
        var summary;

        _this.onEndClass(cls, results);
        if (next) {
          return _this.runClass(next);
        } else {
          _this.onEndFile(_this.current_filename);
          _this.current_filename = null;
          summary = {
            passed: _this.total_passed,
            failed: _this.total_failed,
            time: _this.calcTime(Date.now() - _this.start_time)
          };
          if (typeof _this.onRunEnd === "function") {
            _this.onRunEnd(summary);
          }
          return typeof _this.finished === "function" ? _this.finished(results) : void 0;
        }
      });
    })(next, cls);
  };

  Runner.prototype.calcTime = function(ms) {
    var mins, secs;

    if (ms < 1000) {
      ms = ms.toFixed(2);
      return "" + ms + " ms";
    }
    if ((secs = ms / 1000) < 60) {
      secs = secs.toFixed(2);
      return "" + secs + " secs";
    }
    if ((mins = secs / 60) < 60) {
      mins = mins.toFixed(2);
      return "" + mins + " mins";
    }
  };

  Runner.prototype.loadFile = function(filename) {
    var actual, cls, cwd, func, obj, re;

    cwd = process.cwd();
    if (/\.coffee$/.exec(filename) && !this.coffee_loaded) {
      require("coffee-script/register");
      this.coffee_loaded = true;
    }
    actual = /^\//.exec(filename) ? filename : "" + cwd + "/" + filename;
    obj = require(actual);
    for (cls in obj) {
      func = obj[cls];
      if (this.options.matchClass) {
        re = new RegExp(this.options.matchClass);
        if (!re.exec(cls)) {
          continue;
        }
      }
      if (func.isTwerpTest) {
        this.queue.push([filename, cls, func]);
      }
    }
    return true;
  };

  return Runner;

})();
